### ISSUE TITLE
Feature request: Image background

### ISSUE THREAD

**Issue by scriptex** [codersrank-org/skills-chart-widget#6]
Great widget! Thanks for building this! 

It would be really nice to have the ability to set background color for the widget when used as an image.

My use case does not allow me to specify the background myself because I am using it in a markdown file here on Github. Since Github introduced dark mode, the image is hard to read.

I tried looking into the docs and in the code but couldn't find any option which allows me to set background for the image

**Comment by nolimits4web** [comment]
Add `bg` parameter which is now defaults to white (`#fff`)
